apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.200
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443

apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.201
  selector:
    app: jellyfin
  ports:
    - port: 8096
      targetPort: 8096

apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.202
  selector:
    app: gitlab
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
    - port: 22
      targetPort: 22

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.203
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.204
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090

apiVersion: v1
kind: Service
metadata:
  name: elk
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.205
  selector:
    app: elk
  ports:
    - port: 9200
      targetPort: 9200
    - port: 5601
      targetPort: 5601
    - port: 5044
      targetPort: 5044

apiVersion: v1
kind: Service
metadata:
  name: zabbix
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.206
  selector:
    app: zabbix
  ports:
    - port: 80
      targetPort: 80
    - port: 10051
      targetPort: 10051

apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.207
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080
    - port: 50000
      targetPort: 50000

apiVersion: v1
kind: Service
metadata:
  name: debian-repo
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.208
  selector:
    app: debian-repo
  ports:
    - port: 80
      targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.209
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.210
  selector:
    app: immich
  ports:
    - port: 5432
      targetPort: 5432
