---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitor-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-configs-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juliano-media-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
