---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.204
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-monitor
spec:
  storageClassName: local-nfs-mount
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/k8s-data/monitor"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitor-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
