---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.203
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-monitor
spec:
  storageClassName: local-nfs-mount
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/k8s-data/monitor"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitor-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
