---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.202
  selector:
    app: gitlab
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
    - port: 22
      targetPort: 22

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-gitlab
spec:
  storageClassName: local-nfs-mount
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/k8s-data/gitlab"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
