---
apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.210
  selector:
    app: immich
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-juliano-media
spec:
  storageClassName: local-nfs-mount
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/k8s-data/juliano"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juliano-media-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
spec:
  template:
    spec:
      securityContext:
        runAsUser: 9995
        runAsGroup: 2000
        fsGroup: 2000