---
apiVersion: v1
kind: Service
metadata:
  name: debian-repo
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.208
  selector:
    app: debian-repo
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-repo
spec:
  storageClassName: local-nfs-mount
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/k8s-data/repo"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apt-repo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-repo
  template:
    metadata:
      labels:
        app: debian-repo
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: repo-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: repo-storage
        persistentVolumeClaim:
          claimName: repo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: debian-repo
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.208
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: debian-repo
