### LOADBALANCER IP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.209
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

### PERSISTENT VOLUME STORAGE
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-pgsql
spec:
  storageClassName: local-nfs-mount
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/k8s-data/pgsql"

### PERSISTENT VOLUME CLAIM
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvc
spec:
  storageClassName: local-nfs-mount
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

### SECRET
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: amFzMjMwNVgK

### DEPLOYMENT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 9999
        runAsGroup: 9999
        fsGroup: 9999
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "monitor"
        - name: POSTGRES_USER
          value: "juliano"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: pgsql-pvc

### SERVICE IP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.209
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
